version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: foosball_postgres
    environment:
      POSTGRES_DB: foosball_dev
      POSTGRES_USER: foosball_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foosball_user -d foosball_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Backend service (for later when we want to run full stack)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: foosball_backend
    environment:
      - DB_HOST=db
      - DB_NAME=foosball_dev
      - DB_USER=foosball_user
      - DB_PASSWORD=dev_password
      - ENVIRONMENT=development
      - DEBUG=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - full-stack
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: