
# Foosball TrueSkill Tracker - Docker Compose Configuration
# Development setup: docker-compose up -d
# Database only: docker-compose up db -d
# Full stack: docker-compose up --build

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: foosball_postgres
    environment:
      POSTGRES_DB: foosball_dev
      POSTGRES_USER: foosball_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foosball_user -d foosball_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: foosball_backend
    environment:
      - DB_HOST=db
      - DB_NAME=foosball_dev
      - DB_USER=foosball_user
      - DB_PASSWORD=dev_password
      - ENVIRONMENT=development
      - DEBUG=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Development Server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: foosball_frontend
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
