"""Add rating_history table for TrueSkill tracking

Revision ID: bfe61d6de776
Revises: 0204a1c14e30
Create Date: 2025-07-26 20:43:07.322223

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfe61d6de776"
down_revision: str | Sequence[str] | None = "0204a1c14e30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rating_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("trueskill_mu_before", sa.Float(), nullable=False),
        sa.Column("trueskill_sigma_before", sa.Float(), nullable=False),
        sa.Column("trueskill_mu_after", sa.Float(), nullable=False),
        sa.Column("trueskill_sigma_after", sa.Float(), nullable=False),
        sa.Column("rating_system", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rating_history_id"), "rating_history", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rating_history_id"), table_name="rating_history")
    op.drop_table("rating_history")
    # ### end Alembic commands ###
