"""add team and team_games tables

Revision ID: f649a3bad5e4
Revises: bfe61d6de776
Create Date: 2025-07-28 22:17:16.560972

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f649a3bad5e4"
down_revision: str | Sequence[str] | None = "bfe61d6de776"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player1_id", sa.Integer(), nullable=False),
        sa.Column("player2_id", sa.Integer(), nullable=False),
        sa.Column("trueskill_mu", sa.Float(), nullable=False),
        sa.Column("trueskill_sigma", sa.Float(), nullable=False),
        sa.Column("games_played", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("player1_id != player2_id", name="different_players"),
        sa.CheckConstraint("player1_id < player2_id", name="ordered_players"),
        sa.ForeignKeyConstraint(
            ["player1_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player2_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player1_id", "player2_id", name="unique_team_composition"),
    )
    op.create_index(op.f("ix_teams_id"), "teams", ["id"], unique=False)
    op.create_table(
        "team_games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team1_id", sa.Integer(), nullable=False),
        sa.Column("team2_id", sa.Integer(), nullable=False),
        sa.Column("winner_team_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["team1_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team2_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_team_games_id"), "team_games", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_games_id"), table_name="team_games")
    op.drop_table("team_games")
    op.drop_index(op.f("ix_teams_id"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
